/*
__Seed builder__
  AUTO_GENERATED (Read only)
  Modify via builder
*/

export const SINGULARS =
{
  "actionLogs": "actionLog",
  "actionLog": "actionLog",
  "appInfos": "appInfo",
  "appInfo": "appInfo",
  "arrisCraneStatuses": "arrisCraneStatus",
  "arrisCraneStatus": "arrisCraneStatus",
  "arrisFailures": "arrisFailure",
  "arrisFailure": "arrisFailure",
  "arrisFiles": "arrisFile",
  "arrisFile": "arrisFile",
  "arrisForms": "arrisForm",
  "arrisForm": "arrisForm",
  "arrisOperators": "arrisOperator",
  "arrisOperator": "arrisOperator",
  "contents": "content",
  "content": "content",
  "cranes": "crane",
  "crane": "crane",
  "evidences": "evidence",
  "evidence": "evidence",
  "items": "item",
  "item": "item",
  "maintenances": "maintenance",
  "maintenance": "maintenance",
  "maintenanceCategories": "maintenanceCategory",
  "maintenanceCategory": "maintenanceCategory",
  "maintenanceEvidences": "maintenanceEvidence",
  "maintenanceEvidence": "maintenanceEvidence",
  "maintenanceFiles": "maintenanceFile",
  "maintenanceFile": "maintenanceFile",
  "maintenancePermses": "maintenancePerms",
  "maintenancePerms": "maintenancePerms",
  "maintenanceTypes": "maintenanceType",
  "maintenanceType": "maintenanceType",
  "onedriveAuths": "onedriveAuth",
  "onedriveAuth": "onedriveAuth",
  "operations": "operation",
  "operation": "operation",
  "orders": "order",
  "order": "order",
  "parts": "part",
  "part": "part",
  "securityCategories": "securityCategory",
  "securityCategory": "securityCategory",
  "securityChecks": "securityCheck",
  "securityCheck": "securityCheck",
  "securityCheckTypes": "securityCheckType",
  "securityCheckType": "securityCheckType",
  "securityRevisions": "securityRevision",
  "securityRevision": "securityRevision",
  "shippings": "shipping",
  "shipping": "shipping",
  "suggestions": "suggestion",
  "suggestion": "suggestion",
  "users": "user",
  "user": "user",
};